### ISSUE TITLE
Initial redirection issue

### ISSUE THREAD

**Issue by Mafiasource** [Mafiasource/Mafiasource#15]
**Describe the bug**
Initial visit to base domain (localhost) and without https enabled will throw internal server error.
Root /.htaccess still not functioning correctly without https.

**To Reproduce**
1. Disable HTTPS
2. Visit base domain (without protocol and www)

**Temp. fix**
Only for servers without HTTPS Find / replace https instances with http on lines 91, 95 and 112 in public_html/.htaccess

**Comment by floska** [comment]
Hi, you can make one video tutorial how to install please, i try to install but i get HTTP ERROR 500, or you can help me to install to domain? thank you

**Comment by Mafiasource** [comment]
> Hi, you can make one video tutorial how to install please, i try to install but i get HTTP ERROR 500, or you can help me to install to domain? thank you

Hi can you send me any errors you've encountered either apache or php errors? Thanks!
