### ISSUE TITLE
how i can install it at localhost  or live without virual host

### ISSUE THREAD

**Issue by fisher762** [Mafiasource/Mafiasource#34]
hello
can you tell me how i can install it at subfolder at localhost to be like this 
http://localhost/mafia
i dont want to use virtual host

**Comment by Mafiasource** [comment]
Hi Fisher,

By default Mafiasource cannot be installed from within a subfolder in the doucment root. It is possible however with a few minor changes.
A few months ago i've managed to get the source working from a subfolder with some minor changes.
If you need help with this i'll try to revisit that source code and send you all the details.



Kind regards
Michael

**Comment by fisher762** [comment]
hello :)
yes please send the code to me .. or tell me what and where to change .
because i really need to make it work at localhost with subfolder 
best regards

**Comment by Mafiasource** [comment]
I've written everything out with all changes required which was a fucking bunch and accidentally closed my browser for testing losing all this written crap..
Anyway i'll sent you the whole package soon with only a few changes required for you.. 
I'm fucking pissed at my stupidity.

**Comment by Mafiasource** [comment]
I'm going to give you some work anyway..
# Changes required
## .htaccess
Change SUBDIRECTORY on lines 103-110, 115, 120, 123-126, 131, and 136
Lines 103-110:
```
    RewriteRule ^foto/([0-9]+)x([0-9]+)/([1-3])/([^/]+)/([^/]+)/([^/]+)/([^/]+)/(.*)$ /SUBDIRECTORY/web/public/foto.php?w=$1&h=$2&zc=$3&src=$4/$5/$6/$7/$8 [L,B,NC,QSA]
    RewriteRule ^foto/([0-9]+)x([0-9]+)/([1-3])/([^/]+)/([^/]+)/([^/]+)/(.*)$ /SUBDIRECTORY/web/public/foto.php?w=$1&h=$2&zc=$3&src=$4/$5/$6/$7 [L,B,NC,QSA]
    RewriteRule ^foto/([0-9]+)x([0-9]+)/([^/]+)/([^/]+)/([^/]+)/([^/]+)/(.*)$ /SUBDIRECTORY/web/public/foto.php?w=$1&h=$2&src=$3/$4/$5/$6/$7 [L,B,NC,QSA]
    RewriteRule ^foto/([0-9]+)x([0-9]+)/([^/]+)/([^/]+)/([^/]+)/(.*)$ /SUBDIRECTORY/web/public/foto.php?w=$1&h=$2&src=$3/$4/$5/$6 [L,B,NC,QSA]
    ## Without sizes or zoom crop incl. 2 directory levels deeper.
    RewriteRule ^foto/([^/]+)/([^/]+)/([^/]+)/([^/]+)/([^/]+)/([^/]+)/(.*)$ /SUBDIRECTORY/web/public/foto.php?src=$1/$2/$3/$4/$5/$6/$7 [L,B,NC,QSA]
    RewriteRule ^foto/([^/]+)/([^/]+)/([^/]+)/([^/]+)/(.*)$ /SUBDIRECTORY/web/public/foto.php?src=$1/$2/$3/$4/$5 [L,B,NC,QSA]
    RewriteRule ^foto/([^/]+)/([^/]+)/([^/]+)/(.*)$ /SUBDIRECTORY/web/public/foto.php?src=$1/$2/$3/$4 [L,B,NC,QSA]
```
Line 115:
```
        #RewriteRule (.*) https://%{HTTP_HOST}/SUBDIRECTORY/web/public/images/favicon.ico [R=301,L]
```
Line 120:
```
    RewriteRule (.*) http%1://%{HTTP_HOST}/SUBDIRECTORY/web/public/images/favicon.ico [R=301,L]
```
Lines 123-126:
```
    RewriteCond %{REQUEST_URI} /SUBDIRECTORY/google29f33f42f4b5ccd8.html [or]
    RewriteCond %{REQUEST_URI} /SUBDIRECTORY/robots.txt [or]
    RewriteCond %{REQUEST_URI} /SUBDIRECTORY/sw.js [or]
    RewriteCond %{REQUEST_URI} /SUBDIRECTORY/favicon.ico
```
Line 131:
```
    RewriteRule .? %{ENV:BASE}/SUBDIRECTORY/web/index.php [L]
```
Line 136:
```
        RedirectMatch 302 ^/$ /SUBDIRECTORY/web/index.php/
```
## install/.htaccess
Change SUBDIRECTORY on lines 23 and 39
Line 23:
```
DirectoryIndex /SUBDIRECTORY/install/index.php
```
Line 39:
```
        RedirectMatch 302 ^/$ /SUBDIRECTORY/install/index.php/
```
## app/config/config.php
Add the following lines at the end of the file:
```
// Grab sub directory if applicable based on possible dirRoot names.
define('WINDOWS', (bool)(strtoupper(substr(PHP_OS, 0, 3)) === 'WIN'));
$searchDelimiter = WINDOWS ? '\\' : '/';
$rd = WINDOWS ? '/' : '\\';
$dirs = explode($searchDelimiter, realpath(__DIR__ . $rd . '..' . $rd . '..' . $rd));
$dirRoots = array('www', 'wwwroot', 'htdocs', 'public_html', 'private_html'/*, ... */);
$directory = isset($dirs[count($dirs) - 2]) && in_array($dirs[count($dirs) - 2], $dirRoots) ? '/' . $dirs[count($dirs) - 1] : '';
$searchDelimiter = $rd = $dirs = $dirRoots = null;

define('SUB_DIR', $directory); // If website is hosted a directory under DOCUMENT_ROOT, or empty string.
```
## app/config/routing.php
Change lines 37, 40, 158 and 180 to include the SUB_DIR global.
Line 37:
```
        $this->settings['twigCache'] = DEVELOPMENT === false ? DOC_ROOT . SUB_DIR . '/app/cache/TwigCompilation/' : FALSE;
```
Line 40:
```
        $endRoute = str_replace(SUB_DIR, '', $_SERVER['REQUEST_URI']);
```
Line 158:
```
        return isset($_SESSION['PREV_ROUTE']) ? $_SESSION['PREV_ROUTE'] : SUB_DIR . "/";
```
Line 180:
```
            header('Location: ' . SUB_DIR . $result . $addAfterRoute, true, 301);
```
# app/config/twig.filters.php
Change lines 6 and 7:
```
$twig->addGlobal('docRoot', PROTOCOL . $_SERVER['HTTP_HOST'] . SUB_DIR);
$twig->addGlobal('staticRoot', PROTOCOL . STATIC_SUBDOMAIN . "." . $route->settings['domainBase'] . SUB_DIR);
```
# src/Controllers/.inc.head.php
Change line 24:
```
$pageImage = PROTOCOL.STATIC_SUBDOMAIN.".".$route->settings['domainBase'].SUB_DIR."/web/public/images/mafiasource.jpg";
```
# install/index.php
Change lines 102 and 119
Line 102:
```
        header('Location: '.SUB_DIR.'/install/index.php', TRUE, 301);
```
Line 119:
```
        header('Location: '.SUB_DIR.'/install/index.php?encryption=encrypted', TRUE, 301);
```
## Results
With these changes the source should work in a subdirectory inside htdocs a.k.a. www a.k.a. public_html. Some images will not show on the installation page, this is normal when dealing with a subdirectory installation.

**Comment by Mafiasource** [comment]
I'm going to give you some work anyway..
# Changes required for subdirectory installation
## .htaccess
Change SUBDIRECTORY on lines 103-110, 115, 120, 123-126, 131, and 136
Lines 103-110:
```
RewriteRule ^foto/([0-9]+)x([0-9]+)/([1-3])/([^/]+)/([^/]+)/([^/]+)/([^/]+)/(.*)$ /SUBDIRECTORY/web/public/foto.php?w=$1&h=$2&zc=$3&src=SUBDIRECTORY/$4/$5/$6/$7/$8 [L,B,NC,QSA]
    RewriteRule ^foto/([0-9]+)x([0-9]+)/([1-3])/([^/]+)/([^/]+)/([^/]+)/(.*)$ /SUBDIRECTORY/web/public/foto.php?w=$1&h=$2&zc=$3&src=SUBDIRECTORY/$4/$5/$6/$7 [L,B,NC,QSA]
    RewriteRule ^foto/([0-9]+)x([0-9]+)/([^/]+)/([^/]+)/([^/]+)/([^/]+)/(.*)$ /SUBDIRECTORY/web/public/foto.php?w=$1&h=$2&src=SUBDIRECTORY/$3/$4/$5/$6/$7 [L,B,NC,QSA]
    RewriteRule ^foto/([0-9]+)x([0-9]+)/([^/]+)/([^/]+)/([^/]+)/(.*)$ /SUBDIRECTORY/web/public/foto.php?w=$1&h=$2&src=SUBDIRECTORY/$3/$4/$5/$6 [L,B,NC,QSA]
    ## Without sizes or zoom crop incl. 2 directory levels deeper.
    RewriteRule ^foto/([^/]+)/([^/]+)/([^/]+)/([^/]+)/([^/]+)/([^/]+)/(.*)$ /SUBDIRECTORY/web/public/foto.php?src=SUBDIRECTORY/$1/$2/$3/$4/$5/$6/$7 [L,B,NC,QSA]
    RewriteRule ^foto/([^/]+)/([^/]+)/([^/]+)/([^/]+)/(.*)$ /SUBDIRECTORY/web/public/foto.php?src=SUBDIRECTORY/$1/$2/$3/$4/$5 [L,B,NC,QSA]
    RewriteRule ^foto/([^/]+)/([^/]+)/([^/]+)/(.*)$ /SUBDIRECTORY/web/public/foto.php?src=SUBDIRECTORY/$1/$2/$3/$4 [L,B,NC,QSA]
```
Line 115:
```
        #RewriteRule (.*) https://%{HTTP_HOST}/SUBDIRECTORY/web/public/images/favicon.ico [R=301,L]
```
Line 120:
```
    RewriteRule (.*) http%1://%{HTTP_HOST}/SUBDIRECTORY/web/public/images/favicon.ico [R=301,L]
```
Lines 123-126:
```
    RewriteCond %{REQUEST_URI} /SUBDIRECTORY/google29f33f42f4b5ccd8.html [or]
    RewriteCond %{REQUEST_URI} /SUBDIRECTORY/robots.txt [or]
    RewriteCond %{REQUEST_URI} /SUBDIRECTORY/sw.js [or]
    RewriteCond %{REQUEST_URI} /SUBDIRECTORY/favicon.ico
```
Line 131:
```
    RewriteRule .? %{ENV:BASE}/SUBDIRECTORY/web/index.php [L]
```
Line 136:
```
        RedirectMatch 302 ^/$ /SUBDIRECTORY/web/index.php/
```
## install/.htaccess
Change SUBDIRECTORY on lines 23 and 39
Line 23:
```
DirectoryIndex /SUBDIRECTORY/install/index.php
```
Line 39:
```
        RedirectMatch 302 ^/$ /SUBDIRECTORY/install/index.php/
```
## app/config/config.php
Replace lines 26 (comment "// Others") and 27 with:
```
// Grab sub directory if applicable based on possible dirRoot names.
define('WINDOWS', (bool)(strtoupper(substr(PHP_OS, 0, 3)) === 'WIN'));
$searchDelimiter = WINDOWS ? '\\' : '/';
$rd = WINDOWS ? '/' : '\\';
$dirs = explode($searchDelimiter, realpath(__DIR__ . $rd . '..' . $rd . '..' . $rd));
$dirRoots = array('www', 'wwwroot', 'htdocs', 'public_html', 'private_html'/*, ... */);
$directory = isset($dirs[count($dirs) - 2]) && in_array($dirs[count($dirs) - 2], $dirRoots) ? '/' . $dirs[count($dirs) - 1] : '';
$searchDelimiter = $rd = $dirs = $dirRoots = null;

define('SUB_DIR', $directory); // If website is hosted a directory under DOCUMENT_ROOT, or empty string.

// Others
define('DOC_ROOT',      $_SERVER['DOCUMENT_ROOT'] . SUB_DIR);
```
## app/config/routing.php
Change lines 40, 116, 158 and 180 to include the SUB_DIR global.
Line 40:
```
        $endRoute = str_replace(SUB_DIR, '', $_SERVER['REQUEST_URI']);
```
Line 116:
```
        return SUB_DIR . $result;
```
Line 158:
```
        return isset($_SESSION['PREV_ROUTE']) ? $_SESSION['PREV_ROUTE'] : SUB_DIR . "/";
```
Line 180:
```
            header('Location: ' . SUB_DIR . $result . $addAfterRoute, true, 301);
```
## app/config/twig.filters.php
Change lines 6 and 7:
```
$twig->addGlobal('docRoot', PROTOCOL . $_SERVER['HTTP_HOST'] . SUB_DIR);
$twig->addGlobal('staticRoot', PROTOCOL . STATIC_SUBDOMAIN . "." . $route->settings['domainBase'] . SUB_DIR);
```
## src/Controllers/.inc.head.php
Change line 24:
```
$pageImage = PROTOCOL.STATIC_SUBDOMAIN.".".$route->settings['domainBase'].SUB_DIR."/web/public/images/mafiasource.jpg";
```
## install/index.php
Change lines 102 and 119
Line 102:
```
        header('Location: '.SUB_DIR.'/install/index.php', TRUE, 301);
```
Line 119:
```
        header('Location: '.SUB_DIR.'/install/index.php?encryption=encrypted', TRUE, 301);
```
## install/Views/index.twig
Change line 6:
```
<form name="install" action="{{ docRoot }}/install/index.php" method="POST">
```
## Results
With these changes the source should work in a subdirectory inside htdocs a.k.a. www a.k.a. public_html. Some images will not show on the installation page, this is normal when dealing with a subdirectory installation. After installation however you'll also notice a few missing images, these can be fixed by updating the provided .CSS files to include your SUBDIRECTORY. Also don't forget to also move your /../credentials.php from outside htdocs into htdocs/credentials.php. Good luck!



Kind regards
Michael

**Comment by fisher762** [comment]
Thank you very much for your great effort and wonderful work.
 I will try it today and let you know the result
Best Regards

**Comment by fisher762** [comment]
after i  made all changes that you wrote and install the game .. when i open the url https://localhost/mafia i got blank white page .. the game installed correctly but nothing. 
some times its redirect me to this url 
http://www.localhost/

this is my app/config.php

<?PHP
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
/** Configuration file for some global values used throughout this entire application **/

require_once __DIR__ . '/../../credentials.php'; // Require credentials

// Game, app and web settings
define('BASE_DOMAIN',      "https://localhost/");       // The primary domain
define('STATIC_SUBDOMAIN', "mafia");               // Static subdomain prefix | Has to be a valid subdomain rooted to the same dir of the application's root folder
define('APP_GAMENAME',     "test");          // Gamename, obviously
define('APP_DOMAIN',       BASE_DOMAIN);     // Application runs without www.
define('APP_FB_PAGE',      "Mafiasource");          // Facebook page UNUSED
define('APP_TW_PAGE',      "Mafiasource");          // Twitter page UNUSED
define('APP_GP_PAGE',      "+MafiasourceBe-Nl-En"); // Google plus page UNUSED
define('SSL_ENABLED',      False);                   // HTTPS? true :-) / false :-( ?
define('DEVELOPMENT',      true);                   // Development mode true = on | false = off
define('OFFLINE',          false);                  // Website online / offline for userlogin / game access
define('DEVELOPER_IPS',    json_decode(DEV_IPS));   // Array containing developer IP addresses

// Database credentials
define('PDO_DATABASE',  DBNAME);                                      // Db name
define('PDO_CONSTRING', "mysql:host=localhost;dbname=".PDO_DATABASE); // Db conection string DO NOT CHANGE
define('PDO_DBUSER',    DBUSR);                                       // Db user, generally a user with the least permissions
define('PDO_DBPASS',    DBPWD);                                       // Db password

// Grab sub directory if applicable based on possible dirRoot names.
define('WINDOWS', (bool)(strtoupper(substr(PHP_OS, 0, 3)) === 'WIN'));
$searchDelimiter = WINDOWS ? '\\' : '/';
$rd = WINDOWS ? '/' : '\\';
$dirs = explode($searchDelimiter, realpath(__DIR__ . $rd . '..' . $rd . '..' . $rd));
$dirRoots = array('www', 'wwwroot', 'htdocs', 'public_html', 'private_html'/*, ... */);
$directory = isset($dirs[count($dirs) - 2]) && in_array($dirs[count($dirs) - 2], $dirRoots) ? '/' . $dirs[count($dirs) - 1] : '';
$searchDelimiter = $rd = $dirs = $dirRoots = null;

define('SUB_DIR', $directory); // Website is hosted a directory under DOCUMENT_ROOT.

// Others
define('DOC_ROOT',      $_SERVER['DOCUMENT_ROOT'] . SUB_DIR);

// Mail server settings
define('EMAIL_HOST', "mail.mafiasource.nl");
define('EMAIL_ADDR', "no-reply@mafiasource.nl");
define('EMAIL_PWD',  "noreplypwd");
define('EMAIL_PORT', false);

**Comment by Mafiasource** [comment]
remove https:// from base domain please

**Comment by fisher762** [comment]
i made some changes to twig.filters.php

```
<?PHP

use src\Business\SeoService;

/* TWIG GLOBALS */
$twig->addGlobal('docRoot',"https://localhost/" . SUB_DIR);
$twig->addGlobal('staticRoot',"https://localhost/". SUB_DIR);
```

and change the config.php like what you said and the game open
but  when insert the username and pass to login i got this : 

Forbidden

You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the r

the same when try to register

**Comment by Mafiasource** [comment]
```
$twig->addGlobal('docRoot', PROTOCOL . $_SERVER['HTTP_HOST'] . SUB_DIR);
$twig->addGlobal('staticRoot', PROTOCOL . STATIC_SUBDOMAIN . "." . $route->settings['domainBase'] . SUB_DIR);
```

Please make all changes i proposed exactly like i've written them and retry. Only .htaccess changes should be hard coded and SUBDIRECTORY changed to mafia.

**Comment by Mafiasource** [comment]
Please also var_dump(SUB_DIR) it should display string(6) : "/mafia"

**Comment by fisher762** [comment]
thank you for helping me ..
yes i'm sure of made all changes that you tell me about it .
now i change somethign in .htacess 
i found this \

```
   ## Block unwanted requests not originating from self
    RewriteCond %{REQUEST_METHOD} (POST|CONNECT|DEBUG|DELETE|MOVE|PUT|TRACE|TRACK)
    RewriteCond %{HTTP_REFERER} !^https://(www\.)?mafiasource.nl/.*$ [NC]
    RewriteRule .* - [F]
```

i replace it with this
```
    ## Block unwanted requests not originating from self
    RewriteCond %{REQUEST_METHOD} (POST|CONNECT|DEBUG|DELETE|MOVE|PUT|TRACE|TRACK)
    RewriteCond %{HTTP_REFERER} !^https://(www\.)?localhost/.*$ [NC]
    RewriteRule .* - [F]
```
now when i go to login page i got this image before submit anything
![image](https://github.com/Mafiasource/Mafiasource/assets/410750/3bf4e49c-f875-4d0b-9c58-91548fe3eeaf)


after i log in to the game not all functions work like commit a crime alwyas i got this when press commit
![image](https://github.com/Mafiasource/Mafiasource/assets/410750/2ba72bcd-f7db-4a5f-8896-e9fb2029c8e4)

in the prison i cant buy to go out 
![image](https://github.com/Mafiasource/Mafiasource/assets/410750/d19d51d1-2298-4770-842c-b22a28a306f5)

there is still some paths need to change 
.. 
also register not work it always say username taken
,
if you can please send to me full edited package and i will just change the database connection information and import it .

**Comment by Mafiasource** [comment]
Please show me your hosts file configuraion.
Does your localhost installation allow for HTTPS?

Preparing package now.

**Comment by fisher762** [comment]
i make it without host file .. because i want make this game work multyplayer offline through localhost localnetwork 
let me explain more
if i made virtual host like this .. mafia.localhost and make the chages to hosts file like this
192.168.1.155      mafia.localhost

Now the person on the other device with me on the same network will not be able to open the game via the link
 mafia.localhost
or
mafia.192.168.1.155
.. 
because there is no edited  host file at his computer .. but if i make the game work fine without any issues at my pc with subfolder any one connected to my network can access the game like this
http://192.168.1.155/mafia

i hope you understand what i mean

**Comment by Mafiasource** [comment]
Yes but for that more changes are required. Mafiasource according to /web/index.php only works on the configured domain...
Anyway i've made a perfectly working game without www. or without mafia. or without static. just plain http://localhost/mafia still want it?

**Comment by Mafiasource** [comment]
I'll also insert my test db after install.
Username: MDev pass: 9674742991
Make sure that before testing my package to clear all browser data and cache for localhost

**Comment by fisher762** [comment]
yes that what i need .. let me try it and tell you my friend :)

**Comment by fisher762** [comment]
at the first test its seems like ok but there are some issues .. :
when go to this url http://localhost/mafia/game/stock-exchange
and choose McDopals for test it go to this url   : 
http://localhost/game/stock-exchange/business/McDopals so not found 404
it must be
http://localhost/mafia/game/stock-exchange/business/McDopals

prison buy out not work
![image](https://github.com/Mafiasource/Mafiasource/assets/410750/f1ad0dbe-1659-445d-8d53-ad5eb534648d)

cuz when click the button the url is not correct in console
http://localhost/game/prison/commit-action

carousel in crimes not work .. only 1 crime

i thins this for now .. and all the rest is ok

**Comment by Mafiasource** [comment]
Pro tip: Place {{ docRoot }} in front of broken urls in twig views. Good luck!

**Comment by fisher762** [comment]
you are great ... thank you so much for helping me .. 
i will give you the source when finish translations 
thank you again my friend

**Comment by Mafiasource** [comment]
Would be cool if we could fix those broken URL's on the main branch as well :D

**Comment by fisher762** [comment]
i'm fixing all urls now to work with subfolder..
but how i can run the cron job 
http://localhost/mafia/cronjob/one_minute.php
  
i got 404 not found
![image](https://github.com/Mafiasource/Mafiasource/assets/410750/820c4f42-412b-411f-ad85-3949e6f591b8)

**Comment by Mafiasource** [comment]
Hi Fisher, good luck with that! Our shipper cronjobs are scripts that need to be run by the server itself either through Crontab in Linux or Task Scheduler in Windows. It's normal that these cannot be run buy the end user on demand.

**Comment by fisher762** [comment]
yes i made it with  Windows Task Scheduler  and its works fine now .
i will tell you in any updates :)

**Comment by Mafiasource** [comment]
As this initial issue got resovled i'll be closing this.
